INSERT INTO cocktail (ct_name, ct_glass, ct_garnish, ct_preparation)
VALUES
("Alexander", "Cocktail Glass", "Graded Nutmeg", "Shake all ingredients with ice and strain contents into a cocktail glass. Sprinkle nutmeg on top and serve."),
("Americano", "Old Fashioned Glass", "Orange Slice", "Pour the Campari and vermouth over ice into glass, add a splash of soda water and garnish with half orange slice."),
("Angel Face", "Cocktail Glass", "", "Shake all ingredients with ice and strain contents into a cocktail glass."),
("Aviation", "Cocktail Glass", "Cherry", "Add all ingredients into cocktail shaker filled with ice. Shake well and strain into cocktail glass. Garnish with a cherry."),
("Bacardi", "Cocktail Glass", "Lime Slice", "Shake together with ice. Strain into glass and serve."),
("Between The Sheets", "Cocktail Glass", "", "Pour all ingredients into shaker with ice cubes, shake, strain into chilled cocktail glass."),
("Casino", "Cocktail Glass", "Lemon Twist And Maraschino Cherry", "Pour all ingredients into shaker with ice cubes. Shake well. Strain into chilled cocktail glass. Garnish with a lemon twist and a maraschino cherry. Serve without a straw."),
("Clover Club", "Cocktail Glass", "", "Dry shake ingredients to emulsify, add ice, shake and served straight up."),
("Daiquiri", "Cocktail Glass", "", "Pour all ingredients into shaker with ice cubes. Shake well. Double Strain in chilled cocktail glass."),
("Derby", "Cocktail Glass", "Mint Leaves", "Pour all ingredients into a mixing glass with ice. Stir. Strain into a cocktail glass. Garnish with a sprig of fresh mint in the drink."),
("Dry Martini", "Cocktail Glass", "Olive or Lemon Twist", "Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive."),
("Gin Fizz", "Highball Glass", "Lemon Slice", "	Shake all ingredients with ice cubes, except soda water. Pour into glass. Top with soda water.");

INSERT INTO ingredient (ing_name, ing_amount, ct_id)
VALUES
("Cognac", "3cl", 1),
("Creme De Cacao", "3cl", 1),
("Light Cream", "3cl", 1),
("Campari", "3cl", 2),
("Vermouth Rosso", "3cl", 2),
("Soda Water", "Splash", 2),
("Gin", "3cl", 3),
("Apricot Brandy", "3cl", 3),
("Calvados", "3cl", 3),
("Gin", "4,5cl", 4),
("Creme De Violette", "1,5cl", 4),
("Lemon Juice", "1,5cl", 4),
("Maraschino Liqueur", "1.5cl", 4),
("White Rum", "4,5cl", 5),
("Lime Juice", "2cl", 5),
("Grenadine Syrup", "1cl", 5),
("White Rum", "3cl", 6),
("Cognac", "3cl", 6),
("Cointreau", "3cl", 6),
("Lemon Juice", "2cl", 6),
("Gin (Old Tom)", "4cl", 7),
("Maraschino", "1cl", 7),
("Orange Bitters", "1cl", 7),
("Lemon Juice", "1cl", 7),
("Gin", "4,5cl", 8),
("Lemon Juice", "1,5cl", 8),
("Raspberry Syrup", "1,5cl", 8),
("Egg White", "1 egg worth", 8),
("White Rum", "4,5cl", 9),
("Lime Juice", "2,5cl", 9),
("Simple Syrup", "1,5cl", 9),
("Gin", "6cl", 10),
("Peach Bitters", "2 Dashes", 10),
("Gin", "6cl", 11),
("Dry Vermouth", "1cl", 11),
("Gin", "4,5cl", 12),
("Lemon Juice", "3cl", 12),
("Gomme Syrup", "1cl", 12),
("Soda Water", "8cl", 12);
